//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Account
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Account()
    {
        this.Student = new HashSet<Student>();
        this.Trainer = new HashSet<Trainer>();
    }

    public int ID { get; set; }
    public string UserName { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public int UserType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Student> Student { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Trainer> Trainer { get; set; }
}

public partial class Courses
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Courses()
    {
        this.Section = new HashSet<Section>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public int MajorID { get; set; }

    public virtual Major Major { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Section> Section { get; set; }
}

public partial class Files
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Files()
    {
        this.FileWho = new HashSet<FileWho>();
    }

    public int ID { get; set; }
    public int SectionID { get; set; }
    public string URL { get; set; }
    public System.DateTime DateAdded { get; set; }
    public bool IsDeleted { get; set; }
    public string Description { get; set; }

    public virtual Section Section { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FileWho> FileWho { get; set; }
}

public partial class FileWho
{
    public int FileID { get; set; }
    public int StudentID { get; set; }
    public bool IsDownloaded { get; set; }

    public virtual Files Files { get; set; }
    public virtual Student Student { get; set; }
}

public partial class Major
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Major()
    {
        this.Courses = new HashSet<Courses>();
    }

    public int ID { get; set; }
    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Courses> Courses { get; set; }
}

public partial class Section
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Section()
    {
        this.Files = new HashSet<Files>();
        this.StudentSection = new HashSet<StudentSection>();
    }

    public int SectionID { get; set; }
    public int TrainerID { get; set; }
    public int CourseID { get; set; }
    public System.DateTime DateFrom { get; set; }
    public System.DateTime DateTo { get; set; }
    public System.TimeSpan TimeFrom { get; set; }
    public System.TimeSpan TimeTo { get; set; }
    public bool Sunday { get; set; }
    public bool Monday { get; set; }
    public bool Tuesday { get; set; }
    public bool Wednesday { get; set; }
    public bool Thursday { get; set; }
    public bool Friday { get; set; }
    public bool Saturday { get; set; }

    public virtual Courses Courses { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Files> Files { get; set; }
    public virtual Trainer Trainer { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<StudentSection> StudentSection { get; set; }
}

public partial class Student
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Student()
    {
        this.FileWho = new HashSet<FileWho>();
        this.StudentSection = new HashSet<StudentSection>();
    }

    public int ID { get; set; }
    public string First_Name { get; set; }
    public string Last_Name { get; set; }
    public Nullable<int> AccountID { get; set; }

    public virtual Account Account { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FileWho> FileWho { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<StudentSection> StudentSection { get; set; }
}

public partial class StudentSection
{
    public int StudenID { get; set; }
    public int SectionID { get; set; }
    public decimal FirstMark { get; set; }
    public decimal SecondMark { get; set; }
    public decimal ParticipantionMark { get; set; }
    public decimal FinalMark { get; set; }

    public virtual Section Section { get; set; }
    public virtual Student Student { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Trainer
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Trainer()
    {
        this.Section = new HashSet<Section>();
    }

    public int ID { get; set; }
    public string First_Name { get; set; }
    public string Last_Name { get; set; }
    public string Specialist { get; set; }
    public Nullable<int> AccountID { get; set; }

    public virtual Account Account { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Section> Section { get; set; }
}
